### ISSUE TITLE
An error occurred when the 'number_of_view' was set to 12

### ISSUE THREAD

**Issue by Ayanami2019** [voidstrike/TDPNet#6]
Hello! I got an error while running the code. When I load the dataset, I set the value of ‘number_of_view’ to 12. This error occurred during running:

![bug](https://user-images.githubusercontent.com/49433502/138873431-8577d981-490d-426e-8263-fcf8277a99f7.png)

The reason for the error seems to be due to this line:

https://github.com/voidstrike/TDPNet/blob/ec46e36b1458c28349518993448198dbdef2d4c3/src/trainTDP.py#L174

I tried for a long time and couldn't solve this problem. If you can help me solve it, I will be grateful.

**Comment by voidstrike** [comment]
@Ayanami2019 Hey, there is a `number_of_view` parameter due to some compatible issues with our other projects. In this project, we only consider `number_of_view=1`.

Some potential hints if you want to adopt the method in a multi-view scenario. Assume we use the MVCNN aggregation strategy.
1. Remove the `squeeze(axis=1)` in the line you mentioned, which will now provide a `(batch_size, number_of_view, 224 224)` tensor.
2. Look at [this line](https://github.com/voidstrike/TDPNet/blob/main/src/model/TDPNet.py#L38), it extracts the latent representation of a single image, which results in a `(Batch_size * 512)` tensor.
In your case, you should modify this one to accept a tensor with the aforementioned shape -> this will give you a tensor with shape `(batch_size, number_of_view, 512)`
3. Perform the average (or maximum) operation upon `axis=1` and squeeze it --> you will again get a tensor with `(batch_size, 512)`

Of course, you can try other aggregation methods, as long as the final output of an image (or images) is a 512-D vector (actually, it could be another dimension, but you need to change other parts of the code)

**Comment by Ayanami2019** [comment]
Sorry, my statement may be a bit vague. I feel that for the current code, only one view of the item is used for training for each item, and the other 11 views of the item are not used in the training.The reason seems to be because of this line：
    https://github.com/voidstrike/TDPNet/blob/ec46e36b1458c28349518993448198dbdef2d4c3/src/datasets/mv_dataset.py#L104
It seems that for each item, only the number of 'number_of_view' views are read for training. The running time also seems to prove this point. It only took less than 3 hours to complete the training on the ShapeNet airplane data set(On GTX 1080).
And my running results are also different from what you provided in the paper.
airplane(modelnet): 2.45/13.4(CD/EMD)
I don’t know if my understanding is wrong, I hope you can solve my doubts.

**Comment by voidstrike** [comment]
@Ayanami2019 Yeah, you are right, we use only one image to train the model --> That's why we have "Single View" in the paper title.

But it's a little bit weird to me that you can train airplane in 3 hrs, did you train the model from scratch? (with the --from_scratch and --reclustering ?)
Back to the result, we have 2.34/13.85 (CD/EMD) in the paper and you got 2.45/13.4 (CD/EMD). I believe it's a reasonable difference caused by data split, random point sampling, and so on. Feel free to report the results based on your experiments.

**Comment by Ayanami2019** [comment]
No, no, I think I still haven't expressed my meaning clearly. I know your work is to reconstruct the point cloud from a single view. What I mean is that there are a total of 12 pictures for each item, but it seems that only one picture is used in the code to train the single-view reconstruction network. However, the other 11 images are not used to train the single-view reconstruction network separately, which means that the training sample is only 1/12.
My result was obtained in the ModelNet dataset, and the result you gave in the paper should be (5.44/17.13).
I did train the model from scratch(with the --from_scratch and --reclustering), and it only took 3 hours. 
Based on these two points, I suspect that it is caused by only 1/12 of the training sample.

**Comment by voidstrike** [comment]
@Ayanami2019 Weird, even our newest model achieves 5.14/ 18.43 (CD/EMD) on ModelNet Airplane.
I'm not sure whether your question is the cause, I will try to re-train the ModelNet airplane once I got time.

**Comment by Ayanami2019** [comment]
I think the cause of the problem is here:
https://github.com/voidstrike/TDPNet/blob/ec46e36b1458c28349518993448198dbdef2d4c3/src/datasets/mv_dataset.py#L100-L109
The'views' returned in the'_gititem_' function only reads the pictures with the number of'num_of_view'. Is the corresponding part of your code the same?

**Comment by voidstrike** [comment]
@Ayanami2019 Yeah, this part is identical to mine. I just re-trained the model on ModelNet airplane with the following results. Could you please double-check your results, does it really from ModelNet?

![Screen Shot 2021-10-26 at 11 24 00 PM](https://user-images.githubusercontent.com/7570396/138999897-c28d8391-8fb1-41a0-9126-668a60d1884a.png)

Please try this [model](https://drive.google.com/file/d/1Qne7ERevZcYjcPgUb_Xbu1d2ANOyTXB9/view?usp=sharing) to see if you can get similar results? Or could you please send me your .pt file? (google drive or YXL163430@utdallas.edu)

**Comment by Ayanami2019** [comment]
@voidstrike  I have sent the retrained model to you via email(lixunhfut@163.com). Thanks for your help.

**Comment by Ayanami2019** [comment]
@voidstrike I just forgot to say, I downloaded your model and evaluated the result is correct.

**Comment by voidstrike** [comment]
@Ayanami2019 Hey, I tried the model you sent to me, which gives me the following numbers:
Chamfer Distance  :0.013145923614501953
Earth Mover Distance :0.2256077080965042

Do you get similar results on your side?
I also double-checked the implementation, there are just some modifications for our later project. For example, we add a default category set if `sub_cat` is None.

![Screen Shot 2021-10-27 at 10 32 42 AM](https://user-images.githubusercontent.com/7570396/139098289-22c3d061-cbd5-4edc-871e-56c0a7e168fd.png)

You may notice that there is a `shuffle(views)` at L99. Although we found that this won't affect the final results (that's why we remove it), you can try `from random import shuffle` and add `shuffle(views)` back to see if the results improve. BTW, what's your ShapeNet airplane results, does it correct?

Unfortunately, I'm kind of busy recently thus I might not be able to provide the support that quick.

**Comment by Ayanami2019** [comment]
My result is 0.00235/0.13239. And on the ShapeNet airplane, the result I recorded before is 2.25/10.42.

According to your suggestion, I added shuffle, and the result is correct (5.44/14.76). So I think it is still the problem caused by data loading.
![result](https://user-images.githubusercontent.com/49433502/139169808-b0399b83-dae9-46a7-934a-22416c7e7dc3.png)

It doesn't matter. Thank you very much for taking time out of your busy schedule to help me.
